// SPDX-License-Identifier:
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.6.6. SEE SOURCE BELOW. !!
pragma solidity >=0.7.0 <0.9.0;
pragma experimental ABIEncoderV2;

interface BunchaStructs {
    struct A {
        uint256 a;
    }

    event Event(A[] a, Other.D d);
}

struct B {
    C[] c;
}

struct C {
    Other.E e;
    string d;
}

interface Other {
    struct D {
        B b;
        E e;
    }

    struct E {
        address e;
    }
}

// THIS FILE WAS AUTOGENERATED FROM THE FOLLOWING ABI JSON:
/*
[{"anonymous":false,"inputs":[{"components":[{"internalType":"uint256","name":"a","type":"uint256"}],"indexed":false,"internalType":"struct BunchaStructs.A[]","name":"a","type":"tuple[]"},{"components":[{"components":[{"components":[{"components":[{"internalType":"address","name":"e","type":"address"}],"internalType":"struct Other.E","name":"e","type":"tuple"},{"internalType":"string","name":"d","type":"string"}],"internalType":"struct C[]","name":"c","type":"tuple[]"}],"internalType":"struct B","name":"b","type":"tuple"},{"components":[{"internalType":"address","name":"e","type":"address"}],"internalType":"struct Other.E","name":"e","type":"tuple"}],"indexed":false,"internalType":"struct Other.D","name":"d","type":"tuple"}],"name":"Event","type":"event"}]
*/