require 'hoe'
require './lib/solidity/version.rb'


###
# hack/ quick fix for broken intuit_values - overwrite with dummy
class Hoe
  def intuit_values( input ); end
end



Hoe.spec 'solidity' do

  self.version = Solidity::VERSION

  self.summary = "solidity - (fuzzy) lexer & parser for (crypto) contracts for ethereum & co."
  self.description = summary

  self.urls    = { home: 'https://github.com/rubycocos/blockchain' }

  self.author  = 'Gerald Bauer'
  self.email   = 'wwwmake@googlegroups.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.extra_deps = [
    ['cocos'],
  ]

  self.licenses = ['Public Domain']

  self.spec_extras = {
    required_ruby_version: '>= 2.2.2'
  }

end
