require 'hoe'
require './lib/ellipticcurve/version.rb'

Hoe.spec 'ellipticcurve' do

  self.version = EC::VERSION

  self.summary = "ellipticcurve - elliptic curve digital signature algorithm (ECDSA) cryptography with OpenSSL made easy (incl. secp256k1 curve)"
  self.description = summary

  self.urls    = { home: 'https://github.com/rubycoco/blockchain' }

  self.author  = 'Gerald Bauer'
  self.email   = 'wwwmake@googlegroups.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.extra_deps = [
  ]

  self.licenses = ['Public Domain']

  self.spec_extras = {
    required_ruby_version: '>= 2.3'
  }

end
