require 'hoe'
require './lib/rlp-lite/version.rb'


###
# hack/ quick fix for broken intuit_values - overwrite with dummy
class Hoe
  def intuit_values( input ); end
end



Hoe.spec 'rlp-lite' do

  self.version = Rlp::VERSION

  self.summary = "rlp-lite - light-weight machinery to serialize / deserialze via rlp (recursive length prefix)"
  self.description = summary

  self.urls    = { home: 'https://github.com/rubycocos/blockchain' }

  self.author  = 'Gerald Bauer'
  self.email   = 'wwwmake@googlegroups.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.extra_deps = [
  ]

  self.licenses = ['Public Domain']

  self.spec_extras = {
    required_ruby_version: '>= 2.3'
  }

end

