require 'hoe'


###
# hack/ quick fix for broken intuit_values - overwrite with dummy
class Hoe
  def intuit_values( input ); end
end


Hoe.spec 'abibase' do

  self.version = '0.0.1'

  self.summary = "abibase -  command line tool / helper to manage application binary interfaces (abis)"
  self.description = summary

  self.urls    = { home: 'https://github.com/rubycocos/blockchain' }

  self.author  = 'Gerald Bauer'
  self.email   = 'wwwmake@googlegroups.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.extra_deps = [
    ## ['ethlite'],
    ['etherscan-lite'],
    ['abiparser'],
    ['natspec'],
    ['abidoc'],
    ['abigen'],
  ]

  self.licenses = ['Public Domain']

  self.spec_extras = {
    required_ruby_version: '>= 2.3'
  }

end

