require 'hoe'
require './lib/cryptoquotes/version.rb'

Hoe.spec 'cryptoquotes' do

  self.version = Quotes::VERSION

  self.summary = "cryptoquotes - incl. oracle tool to get a random crypto quote of the day on the command line - on the new new 'in math we trust' ponzi economics - on get-rich-quick blockchain secrets - on bitcon maximalists, scammers, morons, clowns, shills & bagHODLers and more"
  self.description = summary

  self.urls    = { home: 'https://github.com/rubycocos/blockchain' }

  self.author  = 'Gerald Bauer'
  self.email   = 'wwwmake@googlegroups.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.extra_deps = []

  self.licenses = ['Public Domain']

  self.spec_extras = {
    required_ruby_version: '>= 2.3'
  }

end
